# Generated by Django 2.2.10 on 2022-01-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song_store',
            fields=[
                ('title', models.CharField(max_length=15)),
                ('source', models.CharField(max_length=15)),
                ('writer', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('song_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
