# Generated by Django 2.2.10 on 2022-01-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20220103_0915'),
    ]

    operations = [
    ]
