# Generated by Django 2.2.10 on 2022-01-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_info', '0001_initial'),
    ]

    operations = [
    ]
